version: 2
updates:
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    labels:
      - "version-upgrade"
    pull-request-branch-name:
      separator: "_"
    ignore:
      - dependency-name: org.apache.maven.plugins:maven-compiler-plugin

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      
#  - package-ecosystem: npm
#    directory: /ui-super-heroes
#    open-pull-requests-limit: 10
#    schedule:
#      interval: daily
#    labels:
#      - "version-upgrade"
#    pull-request-branch-name:
#      separator: "_"
