quarkus:
  application:
    name: rest-heroes
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    cors: true
    port: 8083
    test-port: 0
  jackson:
    serialization-inclusion: non-empty
  smallrye-openapi:
    info-title: Hero API
    info-description: This API allows CRUD operations on a hero
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio
    servers: "http://localhost:${quarkus.http.port}"
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"
  kubernetes:
    part-of: heroes-service
    annotations:
      "app.openshift.io/connects-to": heroes-db
    env:
      configmaps: "${quarkus.application.name}-config"
    labels:
      app: "${quarkus.application.name}"
      application: "${quarkus.kubernetes.part-of}"
  openshift:
    part-of: "${quarkus.kubernetes.part-of}"
    route:
      expose: true
    annotations:
      "app.openshift.io/connects-to": heroes-db
    env:
      configmaps: "${quarkus.kubernetes.env.configmaps}"
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.openshift.part-of}"

"%prod":
  quarkus:
    datasource:
      username: superman
      password: superman
      reactive:
        url: postgresql://localhost:5432/heroes_database
    hibernate-orm:
      sql-load-script: import.sql
#      database:
#        generation: validate
