version: "3"
services:
  rest-villains-java17:
    image: quay.io/quarkus-super-heroes/rest-villains:java17-latest
    container_name: rest-villains-java17
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      quarkus.hibernate-orm.database.generation: none
      quarkus.hibernate-orm.sql-load-script: no-file
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
