---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-scrape-configs
  labels:
    system: quarkus-super-heroes
data:
  prometheus.yml: |2
# The rest of this will be filled in from ../config/prometheus_scrape_configs.yml via the create-deploy-resources workflow
