---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-villains-config
  labels:
    app: rest-villains
    application: villains-service
data:
  quarkus.hibernate-orm.database.generation: none
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.datasource.jdbc.url: jdbc:postgresql://villains-db:5432/villains_database
