---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: villains-db-config
  labels:
    app: villains-db
    application: villains-service
data:
  POSTGRESQL_DATABASE: dmlsbGFpbnNfZGF0YWJhc2U=
  POSTGRESQL_USERNAME: c3VwZXJiYWQ=
  POSTGRESQL_PASSWORD: c3VwZXJiYWQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: villains-db-init
  labels:
    app: villains-db
    application: villains-service
data:
  get-data.sh: |-
    #!/bin/bash
    
    curl https://raw.githubusercontent.com/edeandrea/quarkus-super-heroes/main/rest-villains/infrastructure/db-init/initialize-tables.sql --output /docker-entrypoint-initdb.d/1-init-tables.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: villains-db
    application: villains-service
    app.kubernetes.io/part-of: villains-service
    app.openshift.io/runtime: postgresql
  name: villains-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: villains-db
  template:
    metadata:
      labels:
        application: villains-service
        name: villains-db
    spec:
      containers:
        - image: bitnami/postgresql:13
          name: villains-db
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: villains-db-config
          volumeMounts:
            - name: villains-db-data
              mountPath: /bitnami/postgresql
            - name: villains-db-init
              mountPath: /docker-entrypoint-preinitdb.d
      volumes:
        - name: villains-db-data
          emptyDir: {}
        - name: villains-db-init
          configMap:
            name: villains-db-init
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: villains-db
    application: villains-service
  name: villains-db
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: villains-db
  type: ClusterIP
