
  villains-db:
    image: postgres:13
    container_name: villains-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../../rest-villains/deploy/db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ../../../rest-villains/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql
