version: "3"
services:

  villains-db:
    image: postgres:13
    container_name: villains-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ./db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql

  rest-villains-native-java11:
    image: quay.io/quarkus-super-heroes/rest-villains:native-java11-latest
    container_name: rest-villains-native-java11
    depends_on:
      - villains-db
    ports:
      - "8084:8084"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://villains-db:5432/villains_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
