---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-heroes-config
  labels:
    app: rest-heroes
    application: heroes-service
data:
  quarkus.hibernate-orm.database.generation: none
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.datasource.reactive.url: postgresql://heroes-db:5432/heroes_database
