---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: heroes-db
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.quarkus.io/commit-id: afcb6962bd8006d222a4f299a21d5d40cdf24f37
    app.quarkus.io/build-timestamp: 2022-02-09 - 19:30:06 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app: rest-heroes
    app.openshift.io/runtime: quarkus
    application: heroes-service
    system: quarkus-super-heroes
    app.kubernetes.io/name: rest-heroes
    app.kubernetes.io/version: java11-latest
    app.kubernetes.io/part-of: heroes-service
  name: rest-heroes
spec:
  template:
    metadata:
      annotations:
        app.openshift.io/connects-to: heroes-db
        app.openshift.io/vcs-ref: main
        app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
        app.quarkus.io/commit-id: afcb6962bd8006d222a4f299a21d5d40cdf24f37
        app.quarkus.io/build-timestamp: 2022-02-09 - 19:30:06 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8083"
        prometheus.io/scheme: http
      labels:
        app: rest-heroes
        app.openshift.io/runtime: quarkus
        application: heroes-service
        system: quarkus-super-heroes
        app.kubernetes.io/name: rest-heroes
        app.kubernetes.io/version: java11-latest
        app.kubernetes.io/part-of: heroes-service
    spec:
      containerConcurrency: 0
      containers:
        - envFrom:
            - configMapRef:
                name: rest-heroes-config
          image: quay.io/quarkus-super-heroes/rest-heroes:java11-latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: null
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: rest-heroes
          ports:
            - containerPort: 8083
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: null
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 256Mi
