---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: heroes-db
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.quarkus.io/commit-id: d7edd4cf024f167b88a1300f0139bc4bc155bae6
    app.quarkus.io/build-timestamp: 2022-02-03 - 21:38:33 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8083"
    prometheus.io/scheme: http
  labels:
    app: rest-heroes
    app.openshift.io/runtime: quarkus
    application: heroes-service
    system: quarkus-super-heroes
    app.kubernetes.io/version: native-java11-latest
    app.kubernetes.io/part-of: heroes-service
    app.kubernetes.io/name: rest-heroes
  name: rest-heroes
spec:
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: d7edd4cf024f167b88a1300f0139bc4bc155bae6
        app.quarkus.io/build-timestamp: 2022-02-03 - 21:38:33 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8083"
        prometheus.io/scheme: http
        app.openshift.io/connects-to: heroes-db
        app.openshift.io/vcs-ref: main
        app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
      labels:
        app: rest-heroes
        app.openshift.io/runtime: quarkus
        application: heroes-service
        system: quarkus-super-heroes
        app.kubernetes.io/version: native-java11-latest
        app.kubernetes.io/part-of: heroes-service
        app.kubernetes.io/name: rest-heroes
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: rest-heroes-config
          image: quay.io/quarkus-super-heroes/rest-heroes:native-java11-latest
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: null
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: rest-heroes
          ports:
            - containerPort: 8083
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: null
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
