version: "3"
services:

  prometheus:
    image: quay.io/prometheus/prometheus:v2.32.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus_scrape_configs.yml:/etc/prometheus/prometheus.yml
