version: "3"
services:

  fights-db:
    image: postgres:14
    container_name: fights-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../../rest-fights/deploy/db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ../../../rest-fights/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql

  apicurio:
    image: apicurio/apicurio-registry-mem:2.1.5.Final
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: true
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    command:
      - "sh"
      - "-c"
      - "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092

  rest-fights-native-java17:
    image: quay.io/quarkus-super-heroes/rest-fights:native-java17-latest
    container_name: rest-fights-native-java17
    depends_on:
      - fights-db
      - apicurio
      - fights-kafka
      - rest-heroes-native-java17
      - rest-villains-native-java17
    ports:
      - "8082:8082"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://fights-db:5432/fights_database
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: validate
      QUARKUS_DATASOURCE_USERNAME: superfight
      QUARKUS_DATASOURCE_PASSWORD: superfight
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: no-file
      QUARKUS_REST_CLIENT_HERO_CLIENT_URL: http://rest-heroes:8083
      FIGHT_VILLAIN_CLIENT_BASE_URL: http://rest-villains:8084
      MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_APICURIO_REGISTRY_URL: http://apicurio:8086/apis/registry/v2
    restart: on-failure
    networks:
      default:
        aliases:
          - rest-fights
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
