version: "3"
services:
  ui-super-heroes-java11:
    image: quay.io/quarkus-super-heroes/ui-super-heroes:java11-latest
    container_name: ui-super-heroes-java11
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
