version: "3"
services:
  rest-heroes-java17:
    image: quay.io/quarkus-super-heroes/rest-heroes:java17-latest
    container_name: rest-heroes-java17
    depends_on:
      - heroes-db
    ports:
      - "8083:8083"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://heroes-db:5432/heroes_database
      quarkus.hibernate-orm.database.generation: none
      quarkus.hibernate-orm.sql-load-script: no-file
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
