version: "3"
services:
  heroes-db:
    image: postgres:13
    container_name: heroes-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init/initialize-database.sql:/docker-entrypoint-initdb.d/1-init-db.sql
      - ./db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/2-init-tables.sql
