---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-statistics-config
  labels:
    app: event-statistics
    application: event-stats
data:
  kafka.bootstrap.servers: PLAINTEXT://fights-kafka:9092
