---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.quarkus.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: d6507bb40f30edfac465b2ae7babb212a8b624e8
    app.quarkus.io/build-timestamp: 2021-12-16 - 19:52:14 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8085"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
    app: event-statistics
    application: event-stats
  name: event-statistics
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8085
  selector:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: fights-kafka
    application: fights-service
  name: fights-kafka
spec:
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    name: fights-kafka
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: fights-zookeeper
    application: fights-service
  name: fights-zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    name: fights-zookeeper
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: event-statistics
    application: event-stats
  name: event-statistics-config
data:
  kafka.bootstrap.servers: PLAINTEXT://fights-kafka:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.quarkus.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: d6507bb40f30edfac465b2ae7babb212a8b624e8
    app.quarkus.io/build-timestamp: 2021-12-16 - 19:52:14 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8085"
    prometheus.io/scheme: http
  labels:
    app: event-statistics
    application: event-stats
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/version: java17-latest
  name: event-statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: event-stats
      app.kubernetes.io/name: event-statistics
      app.kubernetes.io/version: java17-latest
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-ref: main
        app.quarkus.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
        app.quarkus.io/commit-id: d6507bb40f30edfac465b2ae7babb212a8b624e8
        app.quarkus.io/build-timestamp: 2021-12-16 - 19:52:14 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8085"
        prometheus.io/scheme: http
      labels:
        app: event-statistics
        application: event-stats
        app.kubernetes.io/part-of: event-stats
        app.kubernetes.io/name: event-statistics
        app.kubernetes.io/version: java17-latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: event-statistics-config
          image: quay.io/quarkus-super-heroes/event-statistics:java17-latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: event-statistics
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/connects-to: fights-zookeeper
  labels:
    app: fights-kafka
    application: fights-service
    app.kubernetes.io/part-of: fights-service
    app.openshift.io/runtime: kafka
  name: fights-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fights-kafka
  template:
    metadata:
      labels:
        application: fights-service
        name: fights-kafka
    spec:
      containers:
        - command:
            - sh
            - -c
            - "bin/kafka-server-start.sh config/server.properties --override listeners=${KAFKA_LISTENERS}\
              \ --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} --override\
              \ zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}"
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://fights-kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: fights-zookeeper:2181
          image: quay.io/strimzi/kafka:0.26.1-kafka-2.8.1
          name: fights-kafka
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fights-zookeeper
    application: fights-service
    app.kubernetes.io/part-of: fights-service
    app.openshift.io/runtime: kafka
  name: fights-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fights-zookeeper
  template:
    metadata:
      labels:
        application: fights-service
        name: fights-zookeeper
    spec:
      containers:
        - command:
            - sh
            - -c
            - bin/zookeeper-server-start.sh config/zookeeper.properties
          env:
            - name: LOG_DIR
              value: /tmp/logs
          image: quay.io/strimzi/kafka:0.26.1-kafka-2.8.1
          name: fights-zookeeper
          ports:
            - containerPort: 2181
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 64Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.quarkus.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: d6507bb40f30edfac465b2ae7babb212a8b624e8
    app.quarkus.io/build-timestamp: 2021-12-16 - 19:52:14 +0000
  labels:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
    app: event-statistics
    application: event-stats
  name: event-statistics
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: event-statistics
                port:
                  name: http
            path: /
            pathType: Prefix
