---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/connects-to: fights-kafka
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: a9acd68c4e6c8c4c82013a8878266a53d0f1e043
    app.quarkus.io/build-timestamp: 2021-12-21 - 13:35:38 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8085"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
    app: event-statistics
    application: event-stats
    app.openshift.io/runtime: quarkus
  name: event-statistics
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8085
  selector:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: fights-kafka
    application: fights-service
  name: fights-kafka
spec:
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    name: fights-kafka
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/connects-to: fights-kafka
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: a9acd68c4e6c8c4c82013a8878266a53d0f1e043
    app.quarkus.io/build-timestamp: 2021-12-21 - 13:35:38 +0000
  labels:
    name: fights-kafka
    application: event-stats
    app: event-statistics
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/version: java17-latest
    app.kubernetes.io/part-of: event-stats
  name: event-statistics
spec:
  dockerImageRepository: quay.io/quarkus-super-heroes/event-statistics
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: event-statistics
    application: event-stats
  name: event-statistics-config
data:
  kafka.bootstrap.servers: PLAINTEXT://fights-kafka:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fights-kafka
    application: fights-service
    app.kubernetes.io/part-of: fights-service
    app.openshift.io/runtime: kafka
  name: fights-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fights-kafka
  template:
    metadata:
      labels:
        application: fights-service
        name: fights-kafka
    spec:
      containers:
        - command:
            - sh
            - -c
            - "export CLUSTER_ID=$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh\
              \ format -t ${CLUSTER_ID} -c config/kraft/server.properties && bin/kafka-server-start.sh\
              \ config/kraft/server.properties --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS}"
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://fights-kafka:9092
          image: quay.io/strimzi/kafka:0.26.1-kafka-2.8.1
          name: fights-kafka
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 128Mi
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: fights-kafka
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: a9acd68c4e6c8c4c82013a8878266a53d0f1e043
    app.quarkus.io/build-timestamp: 2021-12-21 - 13:35:38 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8085"
    prometheus.io/scheme: http
  labels:
    app: event-statistics
    application: event-stats
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/version: java17-latest
    app.kubernetes.io/part-of: event-stats
  name: event-statistics
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/version: java17-latest
    app.kubernetes.io/part-of: event-stats
  template:
    metadata:
      annotations:
        app.openshift.io/connects-to: fights-kafka
        app.openshift.io/vcs-ref: main
        app.openshift.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
        app.quarkus.io/commit-id: a9acd68c4e6c8c4c82013a8878266a53d0f1e043
        app.quarkus.io/build-timestamp: 2021-12-21 - 13:35:38 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8085"
        prometheus.io/scheme: http
      labels:
        app: event-statistics
        application: event-stats
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: event-statistics
        app.kubernetes.io/version: java17-latest
        app.kubernetes.io/part-of: event-stats
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: event-statistics-config
          image: quay.io/quarkus-super-heroes/event-statistics:java17-latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: event-statistics
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8085
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 256Mi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: fights-kafka
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-url: https://github.com/edeandrea/quarkus-super-heroes
    app.quarkus.io/commit-id: a9acd68c4e6c8c4c82013a8878266a53d0f1e043
    app.quarkus.io/build-timestamp: 2021-12-21 - 13:35:38 +0000
  labels:
    app.kubernetes.io/name: event-statistics
    app.kubernetes.io/part-of: event-stats
    app.kubernetes.io/version: java17-latest
    app: event-statistics
    application: event-stats
    app.openshift.io/runtime: quarkus
  name: event-statistics
spec:
  port:
    targetPort: 8085
  to:
    kind: Service
    name: event-statistics
