name: Build and test JVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    strategy:
#      max-parallel: 1
      fail-fast: false
      matrix:
        java: ['11', '17']
    name: Build and test Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: mvn clean verify
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.test-port=0 -Dmaven.compiler.release=${{ matrix.java }}
