name: Build and test native image

on:
  workflow_run:
    workflows:
      - Build and test JVM
    branches:
      - main
    types:
      - completed

jobs:
  build-native:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup GraalVM
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: mvn clean verify
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.test-port=0 -Pnative
