name: Build and test projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux-java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify

  build-windows-java11:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify

  build-macos-java11:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify

  build-linux-java17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify

  build-windows-java17:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify

  build-macos-java17:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: mvn clean verify
        run: ./mvnw -B clean verify
