name: Build and test JVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
        project:
          - 'event-statistics'
          - 'rest-fights'
          - 'rest-heroes'
          - 'rest-villains'
          - 'ui-super-heroes'
    name: "build-test-${{ matrix.project }}-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: mvn clean verify
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dmaven.compiler.release=${{ matrix.java }}
