name: Build test and push native image

on:
  workflow_run:
    workflows: ["Build and test JVM"]
    branches:
      - main
    types:
      - completed

jobs:
  build-native:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java: ['11', '17']
    name: Build test and push native container images for Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
          uses: actions/setup-java@v2
          with:
            java-version: ${{ matrix.java }}
            distribution: temurin
            cache: maven
#      - name: Setup GraalVM
#        uses: ayltai/setup-graalvm@v1
#        with:
#          java-version: ${{ matrix.java }}
#          graalvm-version: 21.3.0
#          native-image: true
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: setup-java-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Create env vars
        run: |
          echo "QUARKUS_VERSION=$(./mvnw help:evaluate -Dexpression=quarkus.version -q -DforceStdout)" >> $GITHUB_ENV &&
          echo "APP_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create container tag
        run: echo "CONTAINER_TAG=${{ env.APP_VERSION }}-quarkus-${{ env.QUARKUS_VERSION }}-native-java${{ matrix.java }}" >> $GITHUB_ENV
#      - name: Build and test native image
#        run: ./mvnw -B clean verify -Pnative -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.test-port=0
      - name: Build test and push native image
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dmaven.compiler.release=${{ matrix.java }} \
            -Dquarkus.http.host=0.0.0.0 \
            -Dquarkus.http.test-port=0 \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.3-java${{ matrix.java }} \
            -Dquarkus.native.container-build=true \
#            -Dquarkus.native.reuse-existing=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=${{ env.CONTAINER_TAG }} \
            -Dquarkus.container-image.additional-tags=native-java${{ matrix.java }}-latest \
            -Dquarkus.container-image.username=${{ secrets.QUAY_REPO_USERNAME }} \
            -Dquarkus.container-image.password=${{ secrets.QUAY_REPO_TOKEN }}
