name: Create k8s resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

concurrency: create-k8s-resources=${{ github.ref }}

#on:
#  workflow_run:
#    workflows:
#      - "Push Container images"
#    branches:
#      - main
#    types:
#      - completed

#on:
#  workflow_dispatch:

jobs:
  create-k8s-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Generate application k8s resources
        run: scripts/generate-app-k8s-resources.sh

      - name: Merge application k8s resources
        run: scripts/merge-app-k8s-resources.sh

      - name: Merge all applications k8s resources
        run: scripts/merge-all-k8s-resources.sh

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Generate k8s resources
          add: '["**/deploy/*.yml", "deploy/*.yml"]'
          pathspec_error_handling: exitImmediately
