name: Create k8s resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

on:
  workflow_run:
    workflows:
      - "Build and Push Container images"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:
    inputs:
      manual_run:
        type: choice
        description: "Manually run workflow?"
        required: true
        default: "false"
        options:
          - true
          - false

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  create-k8s-resources:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Output status
        run: |
          echo "Event = ${{ github.event.workflow_run }}" && \
          echo "conclusion = ${{ github.event.workflow_run.conclusion }}" && \
          echo "event name = ${{ github.event_name }}" && \
          echo "event ref = ${{ github.event.ref }}" && \
          echo "ref = ${{ github.ref }}"

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Generate application k8s resources
        run: scripts/generate-app-k8s-resources.sh

      - name: Merge application k8s resources
        run: scripts/merge-app-k8s-resources.sh

      - name: Merge all applications k8s resources
        run: scripts/merge-all-k8s-resources.sh

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Generate k8s resources
          add: '["**/deploy/*.yml", "deploy/*.yml"]'
          pathspec_error_handling: exitImmediately
