name: Create deploy resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

on:
  workflow_run:
    workflows:
      - "Build and Push Container images"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}"
  cancel-in-progress: false

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "github.event.workflow_run.event=${{ github.event.workflow_run.event }}"
          echo "github.event.workflow_run.conclusion=${{ github.event.workflow_run.conclusion }}"
          echo "github.repository=${{ github.repository }}"
          echo "github.ref=${{ github.ref }}"

  create-deploy-resources:
    if: ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && ((github.event.workflow_run.event == 'push') || (github.event.workflow_run.event == 'workflow_dispatch')) && (github.event.workflow_run.conclusion == 'success'))) && ((github.repository == 'quarkusio/quarkus-super-heroes') && (github.ref == 'refs/heads/main'))
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Create k8s resources
        shell: bash
        run: scripts/generate-k8s-resources.sh

      - name: Create docker-compose resources
        shell: bash
        run: scripts/generate-docker-compose-resources.sh

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Generate deploy resources (from ${{ github.workflow }} #${{ github.run_number }})"
          add: '["**/deploy/k8s/*.yml", "deploy/k8s/*.yml", "**/deploy/docker-compose/*.yml", "deploy/docker-compose/*.yml", "deploy/db-init/**"]'
          pathspec_error_handling: exitImmediately
