name: Create deploy resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

on:
  workflow_run:
    workflows:
      - "Build and Push Container images"
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  create-deploy-resources:
    if: ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'workflow_run') && (github.event.workflow_run.conclusion == 'success'))) && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Generate application k8s resources
        shell: bash
        run: scripts/generate-app-k8s-resources.sh

      - name: Merge application k8s resources
        shell: bash
        run: scripts/merge-app-k8s-resources.sh

      - name: Merge all applications k8s resources
        shell: bash
        run: scripts/merge-all-k8s-resources.sh

      - name: Create docker-compose resources
        shell: bash
        run: scripts/generate-docker-compose-resources.sh

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Generate k8s resources
          add: '["**/deploy/*.yml", "deploy/*.yml", "**/deploy/docker-compose/*.yml", "deploy/docker-compose/*.yml"]'
          pathspec_error_handling: exitImmediately
