name: Create k8s resources

env:
  IMAGE_BASE_NAME: "quay.io/quarkus-super-heroes"

concurrency: create-k8s-resources=${{ github.ref }}

on:
  workflow_dispatch:

#  workflow_run:
#    workflows:
#      - "Build and test JVM"
#    types:
#      - completed

jobs:
  create-k8s-resources:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind:
          - jvm
          - native
        java:
          - '11'
          - '17'
        project:
#          - 'event-statistics'
#          - 'rest-fights'
#          - 'rest-heroes'
          - rest-villains
    name: "create-k8s-resources-${{ matrix.project }}-java-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Generate application k8s resources
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw package -DskipTests \
            -Dquarkus.container-image.tag=java${{ matrix.java }}-latest \
            -Dquarkus.kubernetes.annotations."app.quarkus.io/vcs-url"=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }} \
            -Dquarkus.kubernetes.annotations."app.quarkus.io/vcs-ref"=${{ env.GITHUB_REF_NAME }} \
            -Dquarkus.openshift.annotations."app.openshift.io/vcs-url"=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }} \
            -Dquarkus.openshift.annotations."app.openshift.io/vcs-ref"=${{ env.GITHUB_REF_NAME }}

      - name: Generate infra k8s resources
        working-directory: ${{ matrix.project}}/deploy/k8s/scripts
        run: create-db-config.sh

      - name: Merge k8s resources
        working-directory: ${{ matrix.project }}/deploy/k8s/scripts
        run: merge-k8s-resources.sh ${{ matrix.kind }} ${{ matrix.java }}

      - name: Commit generated resources
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Generate ${{ matrix.kind }}-java${{ matrix.java }} k8s resources for ${{ matrix.project }}
          add: '["${{ matrix.project }}/deploy/${{ matrix.kind }}-java${{ matrix.java }}-kubernetes.yml", "${{ matrix.project }}/deploy/${{ matrix.kind }}-java${{ matrix.java }}-openshift.yml"]'
          pathspec_error_handling: exitImmediately
