name: Deploy JVM Container images

on:
  workflow_run:
    workflows: ["Build and test JVM"]
    branches:
      - main
    types:
      - completed

jobs:
  push-jvm-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17']
    name: Push JVM container images for Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Create env vars
        run: |
          echo "QUARKUS_VERSION=$(./mvnw help:evaluate -Dexpression=quarkus.version -q -DforceStdout)" >> $GITHUB_ENV &&
          echo "APP_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create container tag
        run: echo "CONTAINER_TAG=${{ env.APP_VERSION }}-quarkus-${{ env.QUARKUS_VERSION }}-java${{ matrix.java }}" >> $GITHUB_ENV
      - name: Push container images
        run: ./mvnw package -DskipTests -Dmaven.compiler.release=${{ matrix.java }} -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.tag=${{ env.CONTAINER_TAG }} -Dquarkus.container-image.username=${{ secrets.QUAY_REPO_USERNAME }} -Dquarkus.container-image.password=${{ secrets.QUAY_REPO_TOKEN }}
