name: Basic build and test

on:
  push:
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  simple-build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        java:
          - '11'
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
    name: "build-test-${{ matrix.project }}-java-${{ matrix.java }}-${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Setup Docker (macos only)
        uses: docker-practice/actions-setup-docker@master
        if: matrix.os == 'macos-latest'

      - name: "build-test-jvm-${{ matrix.project }}-java-${{ matrix.java }}-${{ matrix.os }}"
        working-directory: ${{ matrix.project }}
        run: mvnw -B clean verify -Dquarkus.http.host=0.0.0.0 -Dmaven.compiler.release=${{ matrix.java }}
