name: Basic build and test

env:
  GRAALVM_VERSION: "22.3.0"

on:
  push:
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - 'scripts/deploy-to-azure-containerapps.sh'
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths-ignore:
      - 'deploy/**'
      - '**/*.md'
      - 'docs/**'
      - '**/images/**'
      - '.github/dependabot.yml'
      - 'scripts/deploy-to-azure-containerapps.sh'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-${{ matrix.project }}-java-${{ matrix.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }} \
            -DrunContractVerificationTests=true \
            -DrunConsumerContractTests=true

  native-build-test:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    strategy:
      fail-fast: false
      matrix:
        java:
          - '11'
          - '17'
        project:
          - event-statistics
          - rest-fights
          - rest-heroes
          - rest-villains
    name: "native-build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v3

      - name: Cache and restore GraalVM distro
        id: check-graalvm-cache
        uses: actions/cache@v3
        with:
          path: graalvm-ce-${{ env.GRAALVM_VERSION }}-${{ matrix.java }}.tar.gz
          key: graalvm-ce-distro-${{ env.GRAALVM_VERSION }}-${{ matrix.java }}

      - name: Download GraalVM
        if: steps.check-graalvm-cache.outputs.cache-hit != 'true'
        run: |
          download_url="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${{ env.GRAALVM_VERSION }}/graalvm-ce-java${{ matrix.java }}-linux-amd64-${{ env.GRAALVM_VERSION }}.tar.gz"
          wget -q -O graalvm-ce-${{ env.GRAALVM_VERSION }}-${{ matrix.java }}.tar.gz $download_url

      - name: Setup Maven+OpenJDK Distro
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: graalvm-ce-${{ env.GRAALVM_VERSION }}-${{ matrix.java }}.tar.gz
          java-version: ${{ matrix.java }}
          architecture: x64
          cache: maven

      - name: "build-test-native-${{ matrix.project }}-java-${{ matrix.java }}"
        working-directory: ${{ matrix.project }}
        run: |
          ./mvnw -B clean verify -Pnative \
            -Dquarkus.http.host=0.0.0.0 \
            -Dmaven.compiler.release=${{ matrix.java }} \
            -DrunContractVerificationTests=true \
            -DrunConsumerContractTests=true
  
