version: "3"
services:

  fights-kafka:
    image: quay.io/strimzi/kafka:0.26.1-kafka-2.8.1
    container_name: fights-kafka
    depends_on:
      - fights-zookeeper
    command:
      - "sh"
      - "-c"
      - "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: fights-zookeeper:2181

  fights-zookeeper:
    image: quay.io/strimzi/kafka:0.26.1-kafka-2.8.1
    container_name: fights-zookeeper
    command:
      - "sh"
      - "-c"
      - "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  event-statistics-java17:
    image: quay.io/quarkus-super-heroes/event-statistics:java17-latest
    container_name: event-statistics-java17
    depends_on:
      - fights-kafka
    ports:
      - "8085:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'
